### ISSUE TITLE
有回复但是没有发出

### ISSUE THREAD

**Issue by xueji-x** [Syan-Lin/CyberWaifu#17]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\pycqBot\asyncHttp.py", line 75, in link
    async with self._session.post(url, data=data, allow_redirects=allow_redirects, proxy=proxy, headers=headers) as req:
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 127.0.0.1:5700 ssl:default [远程计算机拒绝网络连 接。]
[2023-05-25 20:43:20,477][asyncHttp_loop/WARNING] PyCqBot: cqAPI 响应: None / {}
[2023-05-25 20:43:25,992][run_on_private_msg_0/INFO] PyCqBot: 发送表情包: 1.png
[2023-05-25 20:43:28,029][asyncHttp_loop/ERROR] PyCqBot: api 请求发生错误 Error: Cannot connect to host 127.0.0.1:5700 ssl:default [远程计算机拒绝网络连接。]
[2023-05-25 20:43:28,030][asyncHttp_loop/ERROR] PyCqBot: Cannot connect to host 127.0.0.1:5700 ssl:default [远程计算机拒绝网络连接。]
Traceback (most recent call last):
  File "D:\coding\anaconda\envs\CyberWaifu\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "D:\coding\anaconda\envs\CyberWaifu\lib\asyncio\base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "D:\coding\anaconda\envs\CyberWaifu\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "D:\coding\anaconda\envs\CyberWaifu\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\coding\anaconda\envs\CyberWaifu\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\coding\anaconda\envs\CyberWaifu\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "D:\coding\anaconda\envs\CyberWaifu\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

**Comment by Syan-Lin** [comment]
给出具体的复现方法
