### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by Prometheus-first** [Syan-Lin/CyberWaifu#4]
人设文件加载成功！(./presets/charactor/大学生.txt)
表情包加载成功！(6 个表情包文件)
记忆导入成功！(5 条记忆)
Traceback (most recent call last):
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\main.py", line 73, in <module>
    waifu.import_memory_dataset(memory)
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\Waifu.py", line 182, in import_memory_dataset
    self.brain.store_memory(chunks)
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\GPT.py", line 40, in store_memory
    self.vectordb.store(text)
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\VectorDB.py", line 23, in store
    vector = self.embedding.embed_documents(text)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 269, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=self.deployment)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 206, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 63, in embed_with_retry
    return _embed_with_retry(**kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 61, in _embed_with_retry
    return embeddings.client.create(**kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

(waifu) E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main>python main.py
[32m
###############################################################################
 ██████╗██╗   ██╗██████╗ ███████╗██████╗ ██╗    ██╗ █████╗ ██╗███████╗██╗   ██╗
██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗██║    ██║██╔══██╗██║██╔════╝██║   ██║
██║      ╚████╔╝ ██████╔╝█████╗  ██████╔╝██║ █╗ ██║███████║██║█████╗  ██║   ██║
██║       ╚██╔╝  ██╔══██╗██╔══╝  ██╔══██╗██║███╗██║██╔══██║██║██╔══╝  ██║   ██║
╚██████╗   ██║   ██████╔╝███████╗██║  ██║╚███╔███╔╝██║  ██║██║██║     ╚██████╔╝
 ╚═════╝   ╚═╝   ╚═════╝ ╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝╚═╝      ╚═════╝
                                                                v1.0  BY Yuan.
###############################################################################
[0m
人设文件加载成功！(./presets/charactor/大学生.txt)
表情包加载成功！(6 个表情包文件)
记忆导入成功！(5 条记忆)
Traceback (most recent call last):
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\main.py", line 73, in <module>
    waifu.import_memory_dataset(memory)
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\Waifu.py", line 182, in import_memory_dataset
    self.brain.store_memory(chunks)
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\GPT.py", line 40, in store_memory
    self.vectordb.store(text)
  File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\VectorDB.py", line 23, in store
    vector = self.embedding.embed_documents(text)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 269, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=self.deployment)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 206, in _get_len_safe_embeddings
    response = embed_with_retry(
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 63, in embed_with_retry
    return _embed_with_retry(**kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 61, in _embed_with_retry
    return embeddings.client.create(**kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

**Comment by Syan-Lin** [comment]
> 人设文件加载成功！(./presets/charactor/大学生.txt) 表情包加载成功！(6 个表情包文件) 记忆导入成功！(5 条记忆) Traceback (most recent call last): File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\main.py", line 73, in waifu.import_memory_dataset(memory) File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\Waifu.py", line 182, in import_memory_dataset self.brain.store_memory(chunks) File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\GPT.py", line 40, in store_memory self.vectordb.store(text) File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\VectorDB.py", line 23, in store vector = self.embedding.embed_documents(text) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 269, in embed_documents return self._get_len_safe_embeddings(texts, engine=self.deployment) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 206, in _get_len_safe_embeddings response = embed_with_retry( File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 63, in embed_with_retry return _embed_with_retry(**kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 289, in wrapped_f return self(f, *args, **kw) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 379, in **call** do = self.iter(retry_state=retry_state) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 314, in iter return fut.result() File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures_base.py", line 451, in result return self.__get_result() File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures_base.py", line 403, in __get_result raise self._exception File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 382, in **call** result = fn(*args, **kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 61, in _embed_with_retry return embeddings.client.create(**kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\embedding.py", line 33, in create response = super().create(*args, **kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 230, in request resp, got_stream = self._interpret_response(result, stream) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response self._interpret_response_line( File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line raise self.handle_error_response( openai.error.AuthenticationError:
> 
> (waifu) E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main>python main.py �[32m ############################################################################### ██████╗██╗ ██╗██████╗ ███████╗██████╗ ██╗ ██╗ █████╗ ██╗███████╗██╗ ██╗ ██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗██║ ██║██╔══██╗██║██╔════╝██║ ██║ ██║ ╚████╔╝ ██████╔╝█████╗ ██████╔╝██║ █╗ ██║███████║██║█████╗ ██║ ██║ ██║ ╚██╔╝ ██╔══██╗██╔══╝ ██╔══██╗██║███╗██║██╔══██║██║██╔══╝ ██║ ██║ ╚██████╗ ██║ ██████╔╝███████╗██║ ██║╚███╔███╔╝██║ ██║██║██║ ╚██████╔╝ ╚═════╝ ╚═╝ ╚═════╝ ╚══════╝╚═╝ ╚═╝ ╚══╝╚══╝ ╚═╝ ╚═╝╚═╝╚═╝ ╚═════╝ v1.0 BY Yuan. ############################################################################### �[0m 人设文件加载成功！(./presets/charactor/大学生.txt) 表情包加载成功！(6 个表情包文件) 记忆导入成功！(5 条记忆) Traceback (most recent call last): File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\main.py", line 73, in waifu.import_memory_dataset(memory) File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\Waifu.py", line 182, in import_memory_dataset self.brain.store_memory(chunks) File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\GPT.py", line 40, in store_memory self.vectordb.store(text) File "E:\study\python奇怪的东西\mybot\cyberwaifu\CyberWaifu-main\waifu\llm\VectorDB.py", line 23, in store vector = self.embedding.embed_documents(text) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 269, in embed_documents return self._get_len_safe_embeddings(texts, engine=self.deployment) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 206, in _get_len_safe_embeddings response = embed_with_retry( File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 63, in embed_with_retry return _embed_with_retry(**kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 289, in wrapped_f return self(f, *args, **kw) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 379, in **call** do = self.iter(retry_state=retry_state) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 314, in iter return fut.result() File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures_base.py", line 451, in result return self.__get_result() File "E:\studySoftware\anaconda\files\envs\waifu\lib\concurrent\futures_base.py", line 403, in __get_result raise self._exception File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\tenacity__init__.py", line 382, in **call** result = fn(*args, **kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\langchain\embeddings\openai.py", line 61, in _embed_with_retry return embeddings.client.create(**kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\embedding.py", line 33, in create response = super().create(*args, **kwargs) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 230, in request resp, got_stream = self._interpret_response(result, stream) File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 624, in _interpret_response self._interpret_response_line( File "E:\studySoftware\anaconda\files\envs\waifu\lib\site-packages\openai\api_requestor.py", line 687, in _interpret_response_line raise self.handle_error_response( openai.error.AuthenticationError:

It's likely caused by wrong openai key. Please check the key.

**Comment by Prometheus-first** [comment]
I replaced my openai key,it seemed that my key is expired,so I bought a new key,but it has another error
  " raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>"
I tried to use VPN,and this problem still exist

**Comment by Prometheus-first** [comment]
I replaced my openai key,it seemed that my key is expired,so I bought a new key,but it has another error
"     raise self.handle_error_response(
openai.error.AuthenticationError: <empty message> "
I tried to use VPN,and this problem still exist

**Comment by Prometheus-first** [comment]
> I replaced my openai key,it seemed that my key is expired,so I bought a new key,but it has another error " raise self.handle_error_response( openai.error.AuthenticationError: " I tried to use VPN,and this problem still exist

![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/2978c6c3-40c4-4938-98fb-e597f03ae9d8)
