### ISSUE TITLE
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

### ISSUE THREAD

**Issue by RyeuXersE** [Syan-Lin/CyberWaifu#8]
作者您好，我按照教程完全安装完毕运行以后出现了server rejected WebSocket connection: HTTP 404的问题，PyCqBot似乎无法正常连接到go-cqhttp websocket 服务，具体运行结果如下，请问如何解决？谢谢！

Microsoft Windows [Version 10.0.19044.2965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\86131>E:

E:\>cd E:\waifu\CyberWaifu-main\CyberWaifu-main

E:\waifu\CyberWaifu-main\CyberWaifu-main>conda activate CyberWaifu

(CyberWaifu) E:\waifu\CyberWaifu-main\CyberWaifu-main>python main.py
[32m
###############################################################################
 ██████╗██╗   ██╗██████╗ ███████╗██████╗ ██╗    ██╗ █████╗ ██╗███████╗██╗   ██╗
██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗██║    ██║██╔══██╗██║██╔════╝██║   ██║
██║      ╚████╔╝ ██████╔╝█████╗  ██████╔╝██║ █╗ ██║███████║██║█████╗  ██║   ██║
██║       ╚██╔╝  ██╔══██╗██╔══╝  ██╔══██╗██║███╗██║██╔══██║██║██╔══╝  ██║   ██║
╚██████╗   ██║   ██████╔╝███████╗██║  ██║╚███╔███╔╝██║  ██║██║██║     ╚██████╔╝
 ╚═════╝   ╚═╝   ╚═════╝ ╚══════╝╚═╝  ╚═╝ ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝╚═╝      ╚═════╝
                                                                v1.0  BY Yuan.
###############################################################################
[0m
人设文件加载成功！(./presets/charactor/大学生.txt)
表情包加载成功！(6 个表情包文件)
记忆数据库存在，不导入记忆

#################################################################
██████╗ ██╗   ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ████████╗
██╔══██╗╚██╗ ██╔╝██╔════╝██╔═══██╗██╔══██╗██╔═══██╗╚══██╔══╝
██████╔╝ ╚████╔╝ ██║     ██║   ██║██████╔╝██║   ██║   ██║
██╔═══╝   ╚██╔╝  ██║     ██║▄▄ ██║██╔══██╗██║   ██║   ██║
██║        ██║   ╚██████╗╚██████╔╝██████╔╝╚██████╔╝   ██║
╚═╝        ╚═╝    ╚═════╝ ╚══▀▀═╝ ╚═════╝  ╚═════╝    ╚═╝
                                            v0.5.1.1  BY FengLiu
#################################################################

[2023-05-20 10:03:28,426][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 Protocol -> device lock is disable. http api may fail.
[2023-05-20 10:03:31,421][MainThread/INFO] PyCqBot: 正在连接 go-cqhttp websocket 服务
Traceback (most recent call last):
  File "E:\waifu\CyberWaifu-main\CyberWaifu-main\main.py", line 78, in <module>
    make_qq_bot(callback, waifu, send_text, send_voice, tts)
  File "E:\waifu\CyberWaifu-main\CyberWaifu-main\qqbot\qqbot.py", line 88, in make_qq_bot
    bot.start(go_cqhttp_path='./qqbot/')
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\site-packages\pycqBot\cqHttpApi.py", line 361, in start
    self._websocket_start()
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\site-packages\pycqBot\cqHttpApi.py", line 401, in _websocket_start
    asyncio.run(main_logic())
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\site-packages\pycqBot\cqHttpApi.py", line 375, in main_logic
    async with websockets.connect(self.__host) as websocket:
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\site-packages\websockets\legacy\client.py", line 637, in __aenter__
    return await self
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\site-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "C:\Users\86131\.conda\envs\CyberWaifu\lib\site-packages\websockets\legacy\client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

(CyberWaifu) E:\waifu\CyberWaifu-main\CyberWaifu-main>Failed to write to log, write /dev/stdout: The pipe is being closed.

**Comment by Syan-Lin** [comment]
似乎是 go-cqhttp 的 config.yml 没配置正确，给出具体的安装步骤，我才能复现这个错误

**Comment by RyeuXersE** [comment]
感谢作者，我自己检查发现是单独运行了go-cqhttp 导致配置文件出错，现在已经解决了。
